# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# See: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore

linter:
  rules:
    # avoid_print: false
    # prefer_single_quotes: true
